import {test} from 'node:test';import assert from 'node:assert/strict';
import {fibPrices,reverseAnchors,drawingKey,FIB_RATIOS} from '../src/fibonacci.ts';
test('Fib prices use native Vela first=0 second=1 convention',()=>{const a={time:1000,price:100},b={time:2000,price:200};const levels=fibPrices(a,b);assert.deepEqual(levels.map(l=>l.ratio),FIB_RATIOS);assert.equal(levels[0].price,100);assert.equal(levels[4].price,161.8);assert.equal(levels[6].price,200);assert.equal(fibPrices(a,b,[1.618])[0].price,261.8);});
test('downward, reversed and equal price anchors without pixel coordinates',()=>{const a={time:1000,price:200},b={time:2000,price:100};assert.equal(fibPrices(a,b)[4].price,138.2);const reversed=reverseAnchors([a,b]);assert.deepEqual(reversed,[b,a]);assert.deepEqual([a,b],[{time:1000,price:200},{time:2000,price:100}]);assert.equal(fibPrices(a,a)[4].price,200);assert.throws(()=>fibPrices({...a,price:NaN},b));assert.throws(()=>reverseAnchors([a]));});
test('drawings persist in isolated security keys, timeframe does not change geometry',()=>{assert.notEqual(drawingKey('sh.600519'),drawingKey('sz.000001'));assert.notEqual(drawingKey('DEMO'),drawingKey('sh.600519'));const anchors=[{time:1704124800000,price:10},{time:1706803200000,price:20}];assert.deepEqual(JSON.parse(JSON.stringify(anchors)),anchors);assert.equal(fibPrices(anchors[0],anchors[1])[3].price,15);});

import {parseRatios,defaultLevels} from '../src/fibonacci.ts';
import {timeline,commit,travel} from '../src/fib-history.ts';
test('ratio input accepts signed decimal extensions, rejects empty duplicate invalid values',()=>{assert.deepEqual(parseRatios('0，.5 1 1.618 -0.2'),[0,.5,1,1.618,-.2]);for(const text of ['', '0,,1','0,0','NaN','Infinity','1e3','101','abc'])assert.throws(()=>parseRatios(text));assert.equal(defaultLevels().length,7);});
test('one logical operation per step, redo branch invalidation and migration',()=>{const h=timeline(null,{drawings:[] as string[]});commit(h,{drawings:['new']});commit(h,{drawings:['dragged']});assert.equal(commit(h,{drawings:['dragged']}),false);assert.deepEqual(travel(h,-1),{drawings:['new']});assert.deepEqual(travel(h,1),{drawings:['dragged']});travel(h,-1);commit(h,{drawings:[]});assert.equal(travel(h,1),undefined);assert.deepEqual(timeline(JSON.parse(JSON.stringify(h)),{drawings:['other']}),h);});
