import {Vela} from '@luxalgo/vela';
import type {IndicatorHandle} from '@luxalgo/vela';
import {aggregate,normalize,parseCSV,example,barReadings,type Dataset,type Period,type Bar} from './core';
import {fibPrices,reverseAnchors,drawingKey,defaultLevels,parseRatios,levelsFrom,FIB_COLORS} from './fibonacci';
import {timeline,commit,travel,type Timeline} from './fib-history';
import type {DrawingsDocument} from '@luxalgo/vela';
import {measurement,reorder,loadNote,saveNote,type Note} from './review';
import {MA_KEY,MA_MAX_LINES,MA_COLORS,defaultMA,loadMA,validateMA,maValues,type MALine} from './ma-settings';
import {followIndicatorReadout} from './indicator-readout';
import workspaceHTML from './workspace.html?raw';
import './style.css';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
type Stock={code:string,code_name:string};
type Reply={data:Dataset,cacheHit:boolean,stale:boolean,error?:string,calendarLatest?:string,dataThrough?:string,checkedThrough?:string,calendarWarning?:string,failedAt?:string};
let catalog:Stock[]=[];
let directoryWarning='';let batchBusy=false;
const inflight=new Map<string,Promise<Reply>>();
let currentReply:Reply|undefined;
async function api<T>(url:string,body?:unknown):Promise<T>{const res=await fetch(url,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).catch(()=>{throw Error('无法连接本机行情服务。请在项目目录运行 npm run service:start，服务恢复后点击重试读取；已有本地记录不受影响。');});if(!res.headers.get('content-type')?.includes('application/json'))throw Error('本机数据服务未运行，请使用 npm run service:start 启动完整版本');const data=await res.json();if(!res.ok)throw Error(data.error??'本机数据请求失败');return data as T;}
function fetchHistory(code:string,force=false):Promise<Reply>{const running=inflight.get(code);if(running)return running;const p=api<Reply>(force?'/api/refresh':'/api/history?code='+encodeURIComponent(code),force?{code}:undefined).finally(()=>inflight.delete(code));inflight.set(code,p);return p;}
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)??'null')??fallback;}catch{return fallback;}}
try{if(!localStorage.getItem('shiri.backup.pre-night.v1')){const snapshot:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(key.startsWith('shiri.')&&!key.startsWith('shiri.backup'))snapshot[key]=localStorage.getItem(key)!;}localStorage.setItem('shiri.backup.pre-night.v1',JSON.stringify({createdAt:new Date().toISOString(),snapshot}));}}catch{/* Quota failure must never replace user records. Export remains available. */}
let watch=read<string[]>('shiri.watch',['sh.600519','sz.000001']).filter(c=>/^(sh|sz|bj)\.\d{6}$/.test(c));
let imports=read<Record<string,Dataset>>('shiri.imports',{});
let selected=read<string>('shiri.selected','sh.600519');if(selected==='DEMO')selected=watch[0]??'sh.600519';
const viewRanges=read<Record<Period,'3M'|'6M'|'1Y'|'ALL'>>('shiri.views.v1',{d:'6M',w:'ALL',m:'ALL'});for(const p of ['d','w','m'] as const)if(!['3M','6M','1Y','ALL'].includes(viewRanges[p]))viewRanges[p]=p==='d'?'6M':'ALL';
let period=read<Period>('shiri.period','d');if(!['d','w','m'].includes(period))period='d';
const enabled=read<Record<string,boolean>>('shiri.indicators',{ma:true,macd:true,rsi:false});
let maExpected:string|null=null;let maConfig=defaultMA();let maWarning='';try{maExpected=localStorage.getItem(MA_KEY);const loaded=loadMA(maExpected);maConfig=loaded.config;maWarning=loaded.warning;}catch{maWarning='均线设置无法读取，暂用 5/10/20；保存前请检查浏览器存储。';}
let chart:Vela|undefined,handles:IndicatorHandle[]=[],dataset:Dataset|undefined,bars:Bar[]=[],request=0;
const cache=new Map<string,Reply>();
let drawingOwner='';let selectedDrawings:string[]=[];let history:Timeline<DrawingsDocument>|undefined;let drawingMuted=false;let gesture=false;let pending=false;let extensions:Record<string,boolean>={};let drawingStorageError='';let expectedDrawings:string|null=null,expectedHistory:string|null=null;
function fibDoc():DrawingsDocument{return {version:1,drawings:chart?.drawings.all().filter(d=>!d.id.startsWith('fib-ray:')).map(d=>({...d,props:{...d.props,extendRight:!!extensions[d.id]}}))??[]};}
function saveDrawings(){if(!chart||!drawingOwner)return;try{const key=drawingKey(drawingOwner),historyKey='shiri.history.v2:'+drawingOwner;if(localStorage.getItem(key)!==expectedDrawings||localStorage.getItem(historyKey)!==expectedHistory){localStorage.setItem('shiri.drawing-conflict.v1:'+drawingOwner+':'+new Date().toISOString(),JSON.stringify({document:fibDoc(),history}));drawingStorageError='另一标签修改了绘图；当前修改已保存为冲突副本，请备份后刷新核对。';$('backupStatus').textContent=drawingStorageError;return;}if(history)localStorage.setItem(historyKey,JSON.stringify(history));localStorage.setItem(key,JSON.stringify(fibDoc()));expectedDrawings=localStorage.getItem(key);expectedHistory=localStorage.getItem(historyKey);drawingStorageError='';}catch{drawingStorageError='绘图存储失败，请检查空间或导出备份。';$('backupStatus').textContent=drawingStorageError;}}
function syncRays(){if(!chart)return;const doc=fibDoc();const rays:DrawingsDocument['drawings']=[];for(const d of doc.drawings){if(d.type!=='fibretracement'||!d.props?.extendRight||d.anchors.length!==2)continue;for(const [i,l] of levelsFrom(d.props).entries()){if(!l.enabled)continue;rays.push({...d,id:`fib-ray:${d.id}:${i}`,type:'hray',anchors:[{time:Math.max(...d.anchors.map(a=>a.time)),price:d.anchors[0].price+l.ratio*(d.anchors[1].price-d.anchors[0].price)}],locked:true,zIndex:d.zIndex-1,style:{...d.style,lineColor:l.color},props:{}});}}drawingMuted=true;chart.drawings.fromJSON({...doc,drawings:[...doc.drawings,...rays]});chart.drawings.select(selectedDrawings.filter(id=>doc.drawings.some(d=>d.id===id)));drawingMuted=false;}
function finishChange(){if(!chart||drawingMuted)return;pending=false;if(history)commit(history,fibDoc());syncRays();saveDrawings();renderDrawings();}
function logical(action:()=>void){if(!chart)return;drawingMuted=true;action();drawingMuted=false;finishChange();}
function destroyChart(){if(pending)finishChange();saveDrawings();chart?.destroy();chart=undefined;history=undefined;drawingOwner='';selectedDrawings=[];renderDrawings();}
function fibRecords(){return fibDoc().drawings;}
const toolNames:Record<string,string>={fibretracement:'Fib回撤',trendline:'趋势线',hline:'水平线',datepricerange:'区间测量'};
function selectedFib(){return fibRecords().find(d=>d.id===selectedDrawings[0]);}
function renderDrawings(){if(!$('fibSelect'))return;const rows=fibRecords();const select=$<HTMLSelectElement>('fibSelect');select.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent=`已保存 ${rows.length} 个图形 · 选择编辑`;select.append(blank);for(const [i,d] of rows.entries()){const o=document.createElement('option');o.value=d.id;o.textContent=`${toolNames[d.type]??d.type} ${i+1} · ${d.anchors.map(a=>a.price.toFixed(2)).join(" → ")}`;select.append(o);}select.value=selectedDrawings[0]??'';for(const id of ['fibDelete','drawingLock','drawingVisible'])$<HTMLButtonElement>(id).disabled=!selectedFib();$<HTMLButtonElement>('fibReverse').disabled=selectedFib()?.anchors.length!==2;$<HTMLButtonElement>('fibSettings').disabled=selectedFib()?.type!=='fibretracement';$<HTMLButtonElement>('fibClear').disabled=!rows.length;$<HTMLButtonElement>('fibUndo').disabled=!history||history.index===0;$<HTMLButtonElement>('fibRedo').disabled=!history||history.index===history.states.length-1;$<HTMLButtonElement>('fib').disabled=!chart;$('fib').classList.toggle('active',chart?.drawings.getTool()==='fibretracement');const d=selectedFib();$('drawingLock').textContent=d?.locked?'解锁':'锁定';$('drawingVisible').textContent=d?.visible===false?'显示':'隐藏';$('fibReadout').textContent=d?.type==='fibretracement'&&d.anchors.length===2?fibPrices(d.anchors[0],d.anchors[1],levelsFrom(d.props).filter(l=>l.enabled).map(l=>l.ratio)).map(l=>`${l.ratio}：${l.price.toFixed(2)}`).join(' · '):d?.type==='datepricerange'&&d.anchors.length===2?measureText(d.anchors[0],d.anchors[1]):'';updateToolButtons();$('fibStatus').textContent=drawingStorageError||(chart?.drawings.getTool()?`绘制${toolNames[chart.drawings.getTool()!]??'图形'}：按提示点击锚点；Escape取消。`:`按股票自动保存${drawingOwner?' · '+drawingOwner:''} · ${d?(d.locked?'已选中锁定图形，解锁后可拖动':'已选中图形，可拖动或设置'):'未选中，点击线或列表选择'}。`);}
function restoreDocument(doc:DrawingsDocument){extensions=Object.fromEntries(doc.drawings.map(d=>[d.id,!!d.props?.extendRight]));chart!.drawings.fromJSON(doc);}
function undoRedo(direction:-1|1){if(!chart||!history)return;const doc=travel(history,direction);if(!doc)return;selectedDrawings=[];drawingMuted=true;chart.drawings.setTool(null);restoreDocument(doc);drawingMuted=false;syncRays();saveDrawings();renderDrawings();}
function setupDrawings(instance:Vela,code:string){drawingOwner=code;drawingStorageError='';expectedDrawings=localStorage.getItem(drawingKey(code));expectedHistory=localStorage.getItem('shiri.history.v2:'+code);selectedDrawings=[];instance.drawings.setStayMode(false).setSnapMode('weak');restoreDocument(read<DrawingsDocument>(drawingKey(code),{version:1,drawings:[]}));history=timeline(read<unknown>('shiri.history.v2:'+code,null),fibDoc());restoreDocument(history.states[history.index]);const changed=()=>{if(chart!==instance||drawingMuted)return;if(gesture){pending=true;return;}finishChange();};instance.on('drawing:created',({id})=>{if(drawingMuted||chart!==instance)return;drawingMuted=true;if(instance.drawings.all().find(d=>d.id===id)?.type==='fibretracement')instance.drawings.update(id,{props:{numbersSize:'normal',labelsSize:'small'}});drawingMuted=false;changed();});instance.on('drawing:edited',changed);instance.on('drawing:removed',changed);instance.on('drawing:selected',({ids})=>{if(chart!==instance||drawingMuted)return;selectedDrawings=ids.filter(id=>!id.startsWith('fib-ray:'));renderDrawings();if(selectedDrawings.length)selectPanel('drawings');});instance.on('drawing:tool',()=>{if(chart===instance&&!drawingMuted)renderDrawings();});syncRays();saveDrawings();renderDrawings();}
window.addEventListener('pointerdown',e=>{if((e.target as HTMLElement).closest('#chart'))gesture=true;},true);
window.addEventListener('pointerup',()=>{gesture=false;if(pending)queueMicrotask(finishChange);},true);
window.addEventListener('pointercancel',()=>{gesture=false;if(pending)finishChange();},true);
function save(){try{localStorage.setItem('shiri.watch',JSON.stringify(watch));localStorage.setItem('shiri.selected',JSON.stringify(selected));localStorage.setItem('shiri.period',JSON.stringify(period));localStorage.setItem('shiri.indicators',JSON.stringify(enabled));}catch{$('status').textContent='浏览器存储空间不足，当前修改无法保存。';}}
function name(code:string){return code==='DEMO'?'合成演示':catalog.find(s=>s.code===code)?.code_name??imports[code]?.name??(code==='sh.600519'?'贵州茅台':code==='sz.000001'?'平安银行':'证券');}
$('app').innerHTML=workspaceHTML;
// Vela dismisses its floating drawing popup on outside pointerdown. Host editing controls
// are part of the same selection context, so keep that press inside our editor.
$('drawingsPanel').addEventListener('pointerdown',e=>e.stopPropagation());
let quotes=read<Record<string,{close:number,change:number,date:string}>>('shiri.quotes.v1',{});
function renderWatch(){const container=$('watch');container.replaceChildren();$('count').textContent=String(watch.length);const q=$<HTMLInputElement>('watchFilter').value.trim().toLowerCase();const order=$<HTMLSelectElement>('watchSort').value;let visible=watch.filter(code=>name(code).toLowerCase().includes(q)||code.includes(q));if(order!=='manual')visible=[...visible].sort((a,b)=>(order==='name'?name(a):a).localeCompare(order==='name'?name(b):b,'zh-CN'));for(const code of visible){const row=document.createElement('div');row.className='watch-row';const btn=document.createElement('button');btn.className='stock'+(selected===code?' active':'');btn.ariaLabel=name(code)+' '+code;const label=document.createElement('span');label.textContent=name(code);const small=document.createElement('small');small.textContent=code;label.append(small);const price=document.createElement('span');price.className='watch-price';const quote=quotes[code];if(quote){price.textContent=quote.close.toFixed(2);const pct=document.createElement('small');pct.textContent=(quote.change>=0?'+':'')+quote.change.toFixed(2)+'%';pct.className=quote.change>=0?'positive':'negative';price.append(pct);price.title='历史日线收盘 '+quote.date;}else price.textContent='未读取';btn.append(label,price);btn.onclick=()=>void load(code);const actions=document.createElement('div');actions.className='watch-row-actions';if(order==='manual')for(const [dir,text] of [[-1,'↑'],[1,'↓']] as const){const move=document.createElement('button');move.textContent=text;move.ariaLabel=(dir===-1?'上移 ':'下移 ')+code;move.disabled=dir===-1?watch.indexOf(code)===0:watch.indexOf(code)===watch.length-1;move.onclick=()=>{watch=reorder(watch,code,dir);save();renderWatch();};actions.append(move);}const rm=document.createElement('button');rm.className='remove';rm.textContent='×';rm.ariaLabel='删除自选 '+code;rm.onclick=()=>{watch=watch.filter(x=>x!==code);save();renderWatch();};actions.append(rm);row.append(btn,actions);container.append(row);}if(!visible.length){container.textContent=q?'自选中暂无匹配':'暂无自选，搜索证券开始复盘。';}}
function renderButtons(){document.querySelectorAll<HTMLButtonElement>('[data-period]').forEach(b=>b.classList.toggle('active',b.dataset.period===period));for(const id of ['ma','macd','rsi'])$(id).classList.toggle('active',enabled[id]);}
let stopIndicatorReadout=()=>{};
function indicators(){stopIndicatorReadout();handles.forEach(h=>h.remove());handles=[];if(!chart)return;if(enabled.ma)maConfig.lines.filter(l=>l.enabled).forEach(l=>handles.push(chart!.addNativeIndicator('sma',{inputs:{length:l.period,color:l.color}})));if(enabled.macd)handles.push(chart.addNativeIndicator('macd'));if(enabled.rsi)handles.push(chart.addNativeIndicator('rsi'));renderMA();const owner=chart,current=handles;stopIndicatorReadout=followIndicatorReadout(current,()=>chart===owner&&handles===current,renderIndicatorReadout,callback=>requestAnimationFrame(callback));}
function metrics(hover?:Bar){const last=hover??bars.at(-1),prev=bars[bars.indexOf(last!)-1];$('metrics').replaceChildren();if(!last)return;$('readoutDate').textContent=(hover?'十字光标 · ':'最新交易日 · ')+last.date;$('summary').textContent=`${bars.at(-1)!.close.toFixed(2)}  元 · ${dataset?.name??name(selected)} · ${{d:'日',w:'周',m:'月'}[period]}线复盘`;$('noteThisDay').textContent='记录 '+(lastHoveredDate??last.date);const entries=barReadings(last,prev);for(const [label,value] of entries){const div=document.createElement('div');div.className='metric';const l=document.createElement('label');l.textContent=label;const b=document.createElement('b');b.textContent=value;if(label==='周期涨跌')b.className=Number.parseFloat(value)>=0?'positive':'negative';div.append(l,b);$('metrics').append(div);}const mas=enabled.ma?maValues(bars.map(b=>b.close),maConfig).filter(l=>l.value!==null).map(l=>'MA'+l.period+' '+l.value!.toFixed(2)):[];$('status').textContent=`${bars.at(-1)!.date} · ${bars.length} 根${{d:'日',w:'周',m:'月'}[period]}K线${mas.length?' · '+mas.join(' / '):''}`;}
function updateMetadata(){if(!dataset)return;const opt=$<HTMLSelectElement>('adjust').options[0];opt.textContent=dataset.adjustment==='none'?'不复权':dataset.adjustment==='synthetic'?'合成样例 · 无复权意义':'用户文件 · 复权未核验';$('source').textContent=`来源：${dataset.source} · 最后成功抓取：${new Date(dataset.fetchedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}（上海）`;$('mode').textContent=selected==='DEMO'?'合成样例 · 非真实价格':imports[selected]?'用户 CSV':'真实日线';$('notice').classList.toggle('demo',selected==='DEMO');$('notice').textContent=selected==='DEMO'?'当前展示算法生成的合成样例，不代表任何股票的真实价格。':imports[selected]?'当前为用户导入数据，价格及复权口径未经本应用核验。':currentReply?.stale?'更新失败，正在显示最后成功的旧缓存：'+currentReply.error+(currentReply.failedAt?' · 失败时间：'+new Date(currentReply.failedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})+'（上海）':''):'真实历史日线来自 BaoStock，非实时行情。只提供不复权；日历和数据日期均采用 Asia/Shanghai。';$('freshness').textContent=!imports[selected]&&selected!=='DEMO'&&currentReply?`行情截至：${currentReply.dataThrough??'暂无交易记录'} · 来源最近交易日：${currentReply.calendarLatest??'日历暂不可用'} · ${currentReply.stale?'旧缓存':currentReply.cacheHit?'缓存命中':'联网读取成功'}${currentReply.calendarWarning?' · 日历：'+currentReply.calendarWarning:''}${directoryWarning?' · 目录：'+directoryWarning:''}${currentReply.dataThrough&&currentReply.calendarLatest&&currentReply.dataThrough<currentReply.calendarLatest?' · 该股数据早于最近交易日，可能停牌或来源待更新':''}`:'';}
function clearMarketReadout(){for(const id of ['summary','indicatorReadout','source','freshness'])$(id).textContent='';$('metrics').replaceChildren();$('readoutDate').textContent='暂无行情读数';lastHoveredDate=undefined;$('noteThisDay').textContent='记录此日';$<HTMLButtonElement>('noteThisDay').disabled=true;}
async function paint(token:number){if(!dataset)return;bars=aggregate(normalize(dataset.rows,dataset.volumeUnit),period);if(!bars.length){destroyChart();$('chart').innerHTML='<div class="state">无有效交易日记录<br>可能尚未上市、长期停牌或来源暂无数据。</div>';clearMarketReadout();$('range').textContent='暂无交易K线';$('status').textContent='来源返回空记录；未生成虚构K线。';updateMetadata();return;}if(!chart){$('chart').replaceChildren();chart=new Vela('#chart',{data:bars,visibleRange:viewRanges[period],timeframe:{d:'1D',w:'1W',m:'1M'}[period],theme:'dark',live:false,drawings:{toolbar:false,tools:['fibretracement','trendline','hline','datepricerange']},animations:false,upColor:'#e76e79',downColor:'#4fb39b'});chart.renderer.set('timezone','Asia/Shanghai');setupDrawings(chart,selected);indicators();const owner=chart;owner.renderer.onCrosshairMove(e=>{if(chart!==owner)return;const b=e.ohlc&&bars.find(b=>b.time===e.ohlc!.time);if(b)lastHoveredDate=b.date;metrics(b??undefined);renderIndicatorReadout();});await chart.ready();}else await chart.setMarket({data:bars,visibleRange:viewRanges[period],timeframe:{d:'1D',w:'1W',m:'1M'}[period]});if(token!==request)return;document.querySelectorAll<HTMLElement>('[data-range]').forEach(b=>b.classList.toggle('active',b.dataset.range===viewRanges[period]));metrics();$<HTMLButtonElement>('noteThisDay').disabled=false;$('refresh').textContent='↻ 更新单股';renderReviewNote();$('range').textContent=`${bars[0].date} — ${bars.at(-1)!.date} · ${{d:'日',w:'周',m:'月'}[period]}线`;updateMetadata();renderMA();}
async function load(code:string,force=false){flushNote();if(noteDirty){$('status').textContent='笔记尚未成功保存，请复制正文或备份后再切换证券。';return;}const token=++request;const switching=selected!==code;if(switching){$<HTMLTextAreaElement>('noteText').disabled=true;lastHoveredDate=undefined;destroyChart();dataset=undefined;currentReply=undefined;bars=[];clearMarketReadout();$('mode').textContent='正在读取';$('notice').textContent='正在读取 '+name(code)+' 的历史日线…';$('range').textContent='正在读取数据…';$('chart').innerHTML='<div class="state">正在加载该股票的真实日线…</div>';}selected=code;save();renderWatch();$('title').textContent=name(code)+' · '+code;$('status').textContent=force?'正在联网更新日线…':'正在读取历史数据…';$('refresh').setAttribute('disabled','');try{let d:Dataset;let reply:Reply|undefined;if(code==='DEMO')d=example();else if(imports[code])d=imports[code];else{reply=!force?cache.get(code):undefined;reply??=await fetchHistory(code,force);d=reply.data;}if(token!==request)return;const daily=normalize(d.rows,d.volumeUnit);const last=daily.at(-1),previous=daily.at(-2);if(last&&code!=='DEMO'){quotes={...read<typeof quotes>('shiri.quotes.v1',{}),...quotes,[code]:{close:last.close,change:previous?(last.close/previous.close-1)*100:0,date:last.date}};try{localStorage.setItem('shiri.quotes.v1',JSON.stringify(quotes));}catch{$('backupStatus').textContent='自选收盘摘要无法保存，行情仍可查看。';}renderWatch();}if(reply)cache.set(code,reply);currentReply=reply;dataset=d;await paint(token);}catch(e){if(token!==request)return;const previous=cache.get(code);if(previous){currentReply={...previous,stale:true,error:e instanceof Error?e.message:'本机数据服务连接失败',failedAt:new Date().toISOString()};dataset=previous.data;await paint(token);return;}destroyChart();dataset=undefined;bars=[];currentReply=undefined;clearMarketReadout();$('chart').innerHTML='<div class="state">本股行情尚未加载<br>服务恢复后点击重试读取，或导入 CSV。</div>';$('status').textContent=e instanceof Error?e.message:'加载失败';$('notice').textContent=$('status').textContent;$('mode').textContent='无可用行情';$('refresh').textContent='↻ 重试读取';$('range').textContent='无可用数据';if(noteOwner!==code)openNote(code,quotes[code]?.date??new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date()));$('source').textContent='';$('freshness').textContent='';}finally{if(token===request)$<HTMLTextAreaElement>('noteText').disabled=false;if(token===request&&!batchBusy)$('refresh').removeAttribute('disabled');}}
$('fib').onclick=()=>armTool('fibretracement');
$('fibCancel').onclick=()=>{chart?.drawings.setTool(null).setMode(null).select(null);renderDrawings();};
$('fibSelect').onchange=()=>{const id=$<HTMLSelectElement>('fibSelect').value;chart?.drawings.setTool(null).select(id?[id]:[]);};
$('fibReverse').onclick=()=>{const d=selectedFib();if(d)logical(()=>chart!.drawings.update(d.id,{anchors:reverseAnchors(d.anchors)}));};
$('fibDelete').onclick=()=>logical(()=>chart!.drawings.removeMany(selectedDrawings));
$('fibUndo').onclick=()=>undoRedo(-1);$('fibRedo').onclick=()=>undoRedo(1);
const clearDialog=$<HTMLDialogElement>('clearDialog'),settingsDialog=$<HTMLDialogElement>('fibDialog');
function closeDialog(dialog:HTMLDialogElement,focus:string){dialog.close();$(focus).focus();}
$('fibClear').onclick=()=>{if(!fibRecords().length||clearDialog.open)return;$('clearMessage').textContent=`${name(drawingOwner)} · ${fibRecords().length} 个图形` ;clearDialog.showModal();$('clearCancel').focus();};
$('clearCancel').onclick=()=>closeDialog(clearDialog,'fibClear');$('clearConfirm').onclick=()=>{logical(()=>chart!.drawings.removeMany(fibRecords().map(d=>d.id)));closeDialog(clearDialog,'fib');};clearDialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(clearDialog,'fibClear');});
let draftLevels=defaultLevels();let settingsId='';
function showLevels(){const box=$('levelRows');box.replaceChildren();draftLevels.forEach((l,i)=>{const row=document.createElement('label');row.className='setting-check';const check=document.createElement('input');check.type='checkbox';check.checked=l.enabled;check.ariaLabel=`显示比例 ${l.ratio}`;check.onchange=()=>{draftLevels[i].enabled=check.checked;};const swatch=document.createElement('span');swatch.className='level-swatch';swatch.style.background=l.color;row.append(check,swatch,document.createTextNode(String(l.ratio)));box.append(row);});}
function parseLevels(){try{const ratios=parseRatios($<HTMLInputElement>('ratios').value);draftLevels=ratios.map((ratio,i)=>draftLevels.find(l=>l.ratio===ratio)??{ratio,color:FIB_COLORS[i%FIB_COLORS.length],enabled:true});showLevels();$('settingsError').textContent='';return true;}catch(e){$('settingsError').textContent=(e as Error).message;return false;}}
$('fibSettings').onclick=()=>{const d=selectedFib();if(!d||settingsDialog.open)return;settingsId=d.id;draftLevels=structuredClone(levelsFrom(d.props));$<HTMLInputElement>('ratios').value=draftLevels.map(l=>l.ratio).join(', ');$<HTMLInputElement>('extendRight').checked=!!d.props?.extendRight;$('settingsError').textContent='';showLevels();settingsDialog.showModal();$('ratios').focus();};
$('parseLevels').onclick=parseLevels;$('defaultLevels').onclick=()=>{draftLevels=defaultLevels();$<HTMLInputElement>('ratios').value=draftLevels.map(l=>l.ratio).join(', ');showLevels();$('settingsError').textContent='';};
$('settingsCancel').onclick=()=>closeDialog(settingsDialog,'fibSettings');settingsDialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(settingsDialog,'fibSettings');});
$('settingsSave').onclick=()=>{if(!parseLevels())return;const d=fibRecords().find(d=>d.id===settingsId);if(!d)return;logical(()=>{extensions[d.id]=$<HTMLInputElement>('extendRight').checked;chart!.drawings.update(d.id,{props:{...d.props,levels:draftLevels}});});closeDialog(settingsDialog,'fibSettings');};
window.addEventListener('keydown',e=>{if(e.isComposing||clearDialog.open||settingsDialog.open||maDialog.open||$<HTMLDialogElement>('helpDialog').open)return;if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.altKey&&['t','h','f','m'].includes(e.key.toLowerCase())){e.preventDefault();armTool(({t:'trendline',h:'hline',f:'fibretracement',m:'datepricerange'} as const)[e.key.toLowerCase() as 't'|'h'|'f'|'m']);return;}if(e.key==='?'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();$<HTMLDialogElement>('helpDialog').showModal();return;}if((e.metaKey||e.ctrlKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();e.stopImmediatePropagation();undoRedo(e.key.toLowerCase()==='y'||e.shiftKey?1:-1);}else if(e.key==='Escape'){document.body.classList.remove('focus-chart');$('focusChart').ariaPressed='false';$('focusChart').textContent='专注图表';chart?.drawings.setTool(null).setMode(null).select(null);renderDrawings();}else if((e.key==='Delete'||e.key==='Backspace')&&selectedDrawings.length){e.preventDefault();e.stopImmediatePropagation();logical(()=>chart!.drawings.removeMany(selectedDrawings));}},true);
window.addEventListener('pagehide',()=>{flushNote();saveDrawings();});window.addEventListener('beforeunload',e=>{flushNote();if(noteDirty)e.preventDefault();});
$('period').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-period]');if(!b||period===b.dataset.period)return;period=b.dataset.period as Period;save();renderButtons();void load(selected);};for(const id of ['ma','macd','rsi'])$(id).onclick=()=>{enabled[id]=!enabled[id];save();renderButtons();indicators();metrics();};$('refresh').onclick=()=>void load(selected,!!dataset);$('demo').onclick=()=>void load('DEMO');
$('search').oninput=()=>{const q=$<HTMLInputElement>('search').value.trim().toLowerCase();const results=$('results');results.replaceChildren();if(!q)return;const known=[...catalog,...Object.keys(imports).filter(c=>!catalog.some(s=>s.code===c)).map(code=>({code,code_name:name(code)}))];const matches=known.filter(s=>s.code_name.toLowerCase().includes(q)||s.code.includes(q));const found=matches.slice(0,20);for(const s of found){const b=document.createElement('button');b.textContent=`${s.code_name} ${s.code} ＋`;b.onclick=()=>{if(!watch.includes(s.code))watch.push(s.code);save();void load(s.code);results.replaceChildren();$<HTMLInputElement>('search').value='';};results.append(b);}if(!found.length)results.textContent='来源沪深上市股票目录暂无匹配，可导入 CSV。';if(matches.length>20){const hint=document.createElement('small');hint.textContent=`共 ${matches.length} 个匹配，显示前20个，请缩小关键词`;results.append(hint);}};
$('file').onchange=async()=>{const f=$<HTMLInputElement>('file').files?.[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('CSV 不得超过 5MB');const source=$<HTMLInputElement>('csvSource').value.trim();if(!source)throw Error('请填写数据来源');const d=parseCSV(await f.text(),$<HTMLInputElement>('code').value.trim(),$<HTMLSelectElement>('unit').value,source);const nextImports={...read<Record<string,Dataset>>('shiri.imports',{}),[d.code]:d};localStorage.setItem('shiri.imports',JSON.stringify(nextImports));imports=nextImports;if(!watch.includes(d.code))watch.push(d.code);save();$('importStatus').textContent='导入成功，已保存到本机浏览器。';await load(d.code);}catch(e){$('importStatus').textContent=e instanceof Error?e.message:'导入失败';}finally{$<HTMLInputElement>('file').value='';}};
$('batch').onclick=async()=>{if(batchBusy)return;const codes=watch.filter(c=>!imports[c]);if(!codes.length){$('batchStatus').textContent='暂无需要联网更新的自选，CSV 文件请重新导入。';return;}batchBusy=true;$('batch').setAttribute('disabled','');$('refresh').setAttribute('disabled','');let ok=0,failed=0;const messages:string[]=[];try{for(let i=0;i<codes.length;i+=30){$('batchStatus').textContent=`正在更新 ${i+1}—${Math.min(i+30,codes.length)} / ${codes.length} 支，请稍候…`;const r=await api<{results:({code:string}&Partial<Reply>)[]}>('/api/batch',{codes:codes.slice(i,i+30)});for(const item of r.results){if(item.data)cache.set(item.code,item as Reply);if(item.error){failed++;messages.push(name(item.code)+'：'+item.error);}else ok++;}}$('batchStatus').textContent=`完成：${ok} 支成功，${failed} 支失败${messages.length?' · '+messages.join('；'):''}`;await load(selected);}catch(e){$('batchStatus').textContent='批量更新中断：'+(e instanceof Error?e.message:'服务异常')+'；已成功更新的数据已缓存，可再次更新。';}finally{batchBusy=false;$('batch').removeAttribute('disabled');$('refresh').removeAttribute('disabled');}};
let lastHoveredDate:string|undefined;
let noteOwner='',noteDay='',noteExpected:string|undefined,noteDirty=false,noteTimer:number|undefined;
function measureText(a:{time:number,price:number},b:{time:number,price:number}){const m=measurement(a,b,bars.map(b=>b.time));return `${m.delta>=0?'+':''}${m.delta.toFixed(2)}元 / ${m.percent>=0?'+':''}${m.percent.toFixed(2)}% · ${m.calendarDays.toFixed(1)}自然日 · 覆盖${m.observedBars}根已加载${{d:'日',w:'周',m:'月'}[period]}K线（含两端）`;}
function armTool(tool:'fibretracement'|'trendline'|'hline'|'datepricerange'){if(!chart)return;chart.drawings.setMode(null).setTool(chart.drawings.getTool()===tool?null:tool);renderDrawings();chart.renderer.focus();}
function updateToolButtons(){for(const [id,tool] of Object.entries({fib:'fibretracement',trend:'trendline',horizontal:'hline',measure:'datepricerange'})){const button=$<HTMLButtonElement>(id);button.disabled=!chart;const active=chart?.drawings.getTool()===tool;button.classList.toggle('active',active);button.ariaPressed=String(active);}const text=chart?.drawings.getTool()?`正在绘制${toolNames[chart.drawings.getTool()!]??'图形'} · Escape取消`:'拖动平移 · 滚轮缩放 · 点击线或右侧图形列表编辑';$('chart').setAttribute('aria-description',text);}
function renderIndicatorReadout(){const readout=chart?.renderer.dataWindowReadout();$('indicatorReadout').textContent=readout?.groups.map(g=>g.name+' '+g.rows.map(r=>r.label+' '+r.value).join(' / ')).join('   ·   ')??'';}
function selectPanel(panel:'watch'|'notes'|'drawings'){for(const [kind,name] of [['watch','Watch'],['notes','Notes'],['drawings','Drawings']] as const){$(kind+'Panel').hidden=kind!==panel;$('tab'+name).setAttribute('aria-selected',String(kind===panel));}document.body.classList.remove('panel-collapsed');$('panelToggle').ariaExpanded='true';$('panelToggle').textContent='收起侧栏';}
function recentNotes(){const list=$('recentNotes');list.replaceChildren();const entries: {date:string,note:Note}[]=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;const prefix='shiri.notes.v1:'+selected+':';if(!key.startsWith(prefix)||key.slice(prefix.length).length!==10)continue;const date=key.slice(prefix.length);try{const note=loadNote(localStorage,selected,date);if(note?.text.trim())entries.push({date,note});}catch{/* Preserve unreadable records. */}}entries.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).forEach(e=>{const b=document.createElement('button');b.className='recent-note';const date=document.createElement('b');date.textContent=e.date;const snippet=document.createElement('span');snippet.textContent=e.note.text.slice(0,55);b.append(date,snippet);b.onclick=()=>{flushNote();if(noteDirty)return;openNote(selected,e.date);};list.append(b);});if(!entries.length)list.textContent='暂无复盘记录，从一个交易日开始。';}
function flushNote(){clearTimeout(noteTimer);if(!noteDirty||!noteOwner||!noteDay)return;try{const r=saveNote(localStorage,noteOwner,noteDay,$<HTMLTextAreaElement>('noteText').value,period,noteExpected);noteExpected=r.note.updatedAt;noteDirty=false;$('noteState').textContent=r.conflict?'另一标签已修改，当前内容保存为冲突副本':'已保存 '+new Date(r.note.updatedAt).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit'});recentNotes();}catch(e){$('noteState').textContent='保存失败：'+(e as Error).message+'，请复制正文或备份';}}
function openNote(code:string,date:string){noteOwner=code;noteDay=date;noteExpected=undefined;noteDirty=false;$('noteSecurity').textContent=name(code)+' · '+code;$<HTMLInputElement>('noteDate').value=date;try{const n=loadNote(localStorage,code,date);noteExpected=n?.updatedAt;$<HTMLTextAreaElement>('noteText').value=n?.text??'';$('noteState').textContent=n?'已保存 · '+new Date(n.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'此日暂无笔记';}catch(e){$<HTMLTextAreaElement>('noteText').value='';$('noteState').textContent=(e as Error).message;}recentNotes();}
function renderReviewNote(){const date=bars.at(-1)?.date;if(!date)return;if(noteOwner!==selected||!noteDay)openNote(selected,date);if(!lastHoveredDate)lastHoveredDate=date;renderIndicatorReadout();}
$('noteText').oninput=()=>{noteDirty=true;$('noteState').textContent='正在编辑…';clearTimeout(noteTimer);noteTimer=window.setTimeout(flushNote,450);};$('noteText').onblur=flushNote;$('noteSave').onclick=flushNote;
$('noteDate').onchange=()=>{flushNote();if(noteDirty){$<HTMLInputElement>('noteDate').value=noteDay;return;}const date=$<HTMLInputElement>('noteDate').value;try{loadNote(localStorage,selected,date);openNote(selected,date);}catch(e){$('noteState').textContent=(e as Error).message;}};
$('noteThisDay').onclick=()=>{flushNote();if(noteDirty)return;openNote(selected,lastHoveredDate??bars.at(-1)?.date??'');selectPanel('notes');$('noteText').focus();};
$('tabWatch').onclick=()=>selectPanel('watch');$('tabNotes').onclick=()=>selectPanel('notes');$('tabDrawings').onclick=()=>selectPanel('drawings');
$('trend').onclick=()=>armTool('trendline');$('horizontal').onclick=()=>armTool('hline');$('measure').onclick=()=>armTool('datepricerange');
$('drawingLock').onclick=()=>{const d=selectedFib();if(d)logical(()=>chart!.drawings.update(d.id,{locked:!d.locked}));};$('drawingVisible').onclick=()=>{const d=selectedFib();if(d)logical(()=>chart!.drawings.update(d.id,{visible:!d.visible}));};
$('watchFilter').oninput=renderWatch;$('watchSort').onchange=renderWatch;
$('viewRange').onclick=e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-range]');if(!button||!chart)return;const preset=button.dataset.range as '3M'|'6M'|'1Y'|'ALL';chart.setVisibleRangePreset(preset);viewRanges[period]=preset;try{localStorage.setItem('shiri.views.v1',JSON.stringify(viewRanges));}catch{$('backupStatus').textContent='显示范围设置无法保存。';}document.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('active',b===button));};
$('panelToggle').onclick=()=>{const collapsed=document.body.classList.toggle('panel-collapsed');$('panelToggle').ariaExpanded=String(!collapsed);$('panelToggle').textContent=collapsed?'展开侧栏':'收起侧栏';};
$('focusChart').onclick=()=>{const active=document.body.classList.toggle('focus-chart');$('focusChart').ariaPressed=String(active);$('focusChart').textContent=active?'退出专注':'专注图表';};
$('help').onclick=()=>{$<HTMLDialogElement>('helpDialog').showModal();$('helpClose').focus();};$('helpClose').onclick=()=>closeDialog($<HTMLDialogElement>('helpDialog'),'help');$<HTMLDialogElement>('helpDialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog($<HTMLDialogElement>('helpDialog'),'help');});
$('backup').onclick=()=>{flushNote();saveDrawings();try{const data:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(key.startsWith('shiri.'))data[key]=localStorage.getItem(key)!;}const file=new Blob([JSON.stringify({application:'CandleScope',version:1,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'});const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download='candlescope-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('backupStatus').textContent='已请求浏览器下载备份，含自选、CSV、图形、历史和笔记；请在下载列表确认文件已保存。';}catch(e){$('backupStatus').textContent='备份失败：'+(e as Error).message;}};

const maDialog=$<HTMLDialogElement>('maDialog');let maDraft:MALine[]=[];
function renderMA(){
 const shown=maConfig.lines.filter(l=>l.enabled);$('ma').textContent='MA'+(enabled.ma?` · ${shown.length}`:'');$('ma').setAttribute('aria-pressed',String(!!enabled.ma));
 const text=enabled.ma?(shown.length?shown.map(l=>'MA'+l.period).join(' / '):'各条均线均已隐藏'):'MA 总开关已关闭';
 $('maSummary').textContent=`${text} · ${period==='d'?'日':period==='w'?'周':'月'}K收盘价简单均线 · 不足期数不绘制${maWarning?' · '+maWarning:''}`;
}
function maRows(){
 const container=$('maRows');container.replaceChildren();
 maDraft.forEach((line,i)=>{
  const row=document.createElement('div');row.className='ma-row';
  const show=document.createElement('label');show.className='ma-show';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=line.enabled;checkbox.ariaLabel=`显示第 ${i+1} 条均线`;checkbox.onchange=()=>{line.enabled=checkbox.checked;};show.append(checkbox,document.createTextNode('显示'));
  const label=document.createElement('label');label.textContent=`周期 ${i+1}`;const input=document.createElement('input');input.type='number';input.min='1';input.max='500';input.step='1';input.inputMode='numeric';input.value=String(line.period);input.ariaLabel=`第 ${i+1} 条均线周期`;input.oninput=()=>{line.period=input.value.trim()===''?NaN:Number(input.value);input.removeAttribute('aria-invalid');};label.append(input);
  const colorLabel=document.createElement('label');colorLabel.textContent='颜色';const color=document.createElement('input');color.type='color';color.value=line.color;color.ariaLabel=`第 ${i+1} 条均线颜色`;color.oninput=()=>{line.color=color.value;};colorLabel.append(color);
  const remove=document.createElement('button');remove.type='button';remove.textContent='删除';remove.ariaLabel=`删除第 ${i+1} 条均线`;remove.disabled=maDraft.length===1;remove.onclick=()=>{maDraft.splice(i,1);maRows();$('maAdd').focus();};
  row.append(show,label,colorLabel,remove);container.append(row);
 });$<HTMLButtonElement>('maAdd').disabled=maDraft.length>=MA_MAX_LINES;$('maCount').textContent=`${maDraft.length} / 8 条；允许全部隐藏`;
}
$('maSettings').onclick=()=>{if(maDialog.open)return;maDraft=structuredClone(maConfig.lines);$('maError').textContent=maWarning;maRows();maDialog.showModal();maDialog.querySelector<HTMLInputElement>('input[type=number]')?.focus();};
$('maAdd').onclick=()=>{if(maDraft.length>=MA_MAX_LINES)return;let n=5;while(maDraft.some(l=>l.period===n))n++;maDraft.push({period:n,enabled:true,color:MA_COLORS[maDraft.length]});maRows();maDialog.querySelectorAll<HTMLInputElement>('input[type=number]').item(maDraft.length-1)?.focus();};
$('maDefault').onclick=()=>{maDraft=defaultMA().lines;$('maError').textContent='默认 5/10/20 已放入草稿；保存后生效。';maRows();};
$('maCancel').onclick=()=>closeDialog(maDialog,'maSettings');maDialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(maDialog,'maSettings');});
$('maSave').onclick=()=>{
 try{const next=validateMA({version:1,lines:maDraft});if(localStorage.getItem(MA_KEY)!==maExpected)throw Error('另一标签修改了均线配置；请刷新后再编辑，当前未覆盖。');const raw=JSON.stringify(next);localStorage.setItem(MA_KEY,raw);maExpected=raw;maConfig=next;maWarning='';indicators();renderMA();metrics();closeDialog(maDialog,'maSettings');}
 catch(e){$('maError').textContent=(e as Error).message;const invalid=maDraft.findIndex(l=>!Number.isInteger(l.period)||l.period<1||l.period>500);if(invalid>=0){const input=maDialog.querySelectorAll<HTMLInputElement>('input[type=number]').item(invalid);input?.setAttribute('aria-invalid','true');input?.focus();}}
};

async function boot(){renderWatch();renderButtons();renderMA();try{const d=await api<{stocks:Stock[],fetchedAt:string,stale:boolean,warning?:string}>('/api/directory');catalog=d.stocks;directoryWarning=d.stale?(d.warning??'旧目录'):'';$('coverage').textContent=`BaoStock 覆盖 ${catalog.length} 支上市沪深 A 股（上海 ${catalog.filter(s=>s.code.startsWith('sh.')).length} / 深圳 ${catalog.filter(s=>s.code.startsWith('sz.')).length}），含主板、科创板、创业板。`;renderWatch();}catch(e){directoryWarning=e instanceof Error?e.message:'目录加载失败';$('coverage').textContent='目录暂不可用：'+directoryWarning+'。';}await load(selected);}
void boot();
